<a href="https://colab.research.google.com/github/stevenhastings/NFL_openCV/blob/main/Kaggle_NFL_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [430]:
import pandas as pd 
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_colwidth', 1000)

# ***GAMES***
### Schema:
* gameId: Game identifier, unique (numeric)
* season: Season of game (numeric)
* week: Week of game (numeric)
* gameDate: Game Date (time, mm/dd/yyyy)
* gameTimeEastern: Start time of game (time, HH:MM:SS, EST)
* homeTeamAbbr: Home team three-letter code (text)
* visitorTeamAbbr: Visiting team three-letter code (text)

In [431]:
games = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/games.csv")

In [432]:
print(games.info())

games.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   gameId           122 non-null    int64
 1   season           122 non-null    int64
 2   week             122 non-null    int64
 3   gameDate         122 non-null    object
 4   gameTimeEastern  122 non-null    object
 5   homeTeamAbbr     122 non-null    object
 6   visitorTeamAbbr  122 non-null    object
dtypes: int64(3), object(4)
memory usage: 6.8+ KB
None

,gameId,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr
0,2021090900,2021,1,09/09/2021,20:20:00,TB,DAL
1,2021091200,2021,1,09/12/2021,13:00:00,ATL,PHI
2,2021091201,2021,1,09/12/2021,13:00:00,BUF,PIT
3,2021091202,2021,1,09/12/2021,13:00:00,CAR,NYJ
4,2021091203,2021,1,09/12/2021,13:00:00,CIN,MIN

Get all game IDs for each team

In [433]:
# games[games['visitorTeamAbbr'] == 'JAX']['gameId'].values

In [434]:
BrownsGameIds = [2021091209, 2021100305, 2021101009, 2021091902, 2021092601, 2021101708, 2021102100, 2021103103]
PatriotsGameIds = [2021091210, 2021092605, 2021100313, 2021101710, 2021102403, 2021091906, 2021101003, 2021103108]
BuccaneersGameIds = [2021092611, 2021100313, 2021101400, 2021103111, 2021090900, 2021091910, 2021101007, 2021102409]
RamsGameIds = [2021091213, 2021092611, 2021100309, 2021102406, 2021091903, 2021100700, 2021101706, 2021103105]
VikingsGameIds = [2021091203, 2021091909, 2021101702, 2021092612, 2021100305, 2021101005, 2021103112]
BroncosGameIds = [2021092609, 2021100311, 2021101709, 2021103110, 2021091212, 2021091904, 2021101006, 2021102100]
RavensGameIds = [2021091300, 2021092602, 2021100311, 2021091913, 2021101100, 2021101701, 2021102400]
SeahawksGameIds = [2021091912, 2021100700, 2021102500, 2021103109, 2021091206, 2021092612, 2021100310, 2021101711]
ChargersGameIds = [2021091208, 2021092604, 2021101701, 2021091911, 2021100400, 2021101009, 2021103108]
CardinalsGameIds = [2021091909, 2021101011, 2021102408, 2021102800, 2021091207, 2021092603, 2021100309, 2021101708]
SteelersGameIds = [2021091201, 2021100312, 2021103103, 2021091908, 2021092607, 2021101006, 2021101711]
JaguarsGameIds = [2021091904, 2021092603, 2021101004, 2021101700, 2021091205, 2021093000, 2021103109]
FalconsGameIds = [2021091200, 2021100300, 2021101000, 2021103100, 2021091910, 2021092606, 2021102402]
RaidersGameIds = [2021091300, 2021092610, 2021101010, 2021102407, 2021091908, 2021100400, 2021101709]
BearsGameIds = [2021091901, 2021100302, 2021101703, 2021103102, 2021091213, 2021092601, 2021101010, 2021102409]
GiantsGameIds = [2021091212, 2021092606, 2021101706, 2021102404, 2021091600, 2021100306, 2021101012, 2021110100]
TitansGameIds = [2021091207, 2021092608, 2021101800, 2021102405, 2021091912, 2021100307, 2021101004, 2021103106]
BillsGameIds = [2021091201, 2021092600, 2021100301, 2021103101, 2021091905, 2021101013, 2021101800]
PanthersGameIds = [2021091202, 2021091900, 2021101001, 2021101702, 2021092300, 2021100303, 2021102404, 2021103100]
LionsGameIds = [2021091204, 2021092602, 2021101704, 2021103104, 2021092000, 2021100302, 2021101005, 2021102406]
TexansGameIds = [2021091205, 2021092300, 2021101003, 2021103105, 2021091902, 2021100301, 2021101705, 2021102408]
ColtsGameIds = [2021091206, 2021091903, 2021101705, 2021103106, 2021092608, 2021100304, 2021101100, 2021102410]
CommandersGameIds = [2021091208, 2021091600, 2021101008, 2021101707, 2021092600, 2021100300, 2021102401, 2021103110]
ChiefsGameIds = [2021091209, 2021092604, 2021101013, 2021110100, 2021091913, 2021100308, 2021101707, 2021102405]
EaglesGameIds = [2021091907, 2021100308, 2021101400, 2021091200, 2021092700, 2021101001, 2021102407, 2021103104]
SaintsGameIds = [2021091211, 2021100306, 2021103111, 2021091900, 2021092605, 2021101008, 2021102500]
JetsGameIds = [2021091906, 2021100307, 2021103107, 2021091202, 2021092609, 2021101000, 2021102403]
DolphinsGameIds = [2021091905, 2021100304, 2021102402, 2021091210, 2021092610, 2021101007, 2021101700, 2021103101]
BengalsGameIds = [2021091203, 2021093000, 2021101002, 2021091901, 2021092607, 2021101704, 2021102400, 2021103107]
PackersGameIds = [2021092000, 2021100312, 2021102401, 2021091211, 2021092613, 2021101002, 2021101703, 2021102800]
SanFranciscoGameIds = [2021092613, 2021100310, 2021102410, 2021091204, 2021091907, 2021101011, 2021103102]
CowboysGameIds = [2021092700, 2021100303, 2021101012, 2021090900, 2021091911, 2021101710, 2021103112]

# Teams

#### Names

In [435]:
teamAbbr = {'CLE':{'Name': 'Browns', 'GameIds': BrownsGameIds}, 
            'NE': {'Name': 'Patriots', 'GameIds': PatriotsGameIds}, 
            'TB': {'Name': 'Buccaneers', 'GameIds': BuccaneersGameIds}, 
            'LA': {'Name': 'Rams', 'GameIds': RamsGameIds}, 
            'MIN': {'Name': 'Vikings', 'GameIds': VikingsGameIds}, 
            'DEN': {'Name': 'Broncos', 'GameIds': BroncosGameIds},
            'BAL': {'Name': 'Ravens', 'GameIds': RavensGameIds}, 
            'SEA': {'Name': 'Seahawks', 'GameIds': SeahawksGameIds}, 
            'LAC': {'Name': "Chargers", 'GameIds': ChargersGameIds}, 
            'ARI': {'Name': 'Cardinals', 'GameIds': CardinalsGameIds},
            'PIT': {'Name': 'Steelers', 'GameIds': SteelersGameIds}, 
            'JAX': {'Name': 'Jaguars', 'GameIds': JaguarsGameIds},
            'ATL': {'Name': 'Falcons', 'GameIds': FalconsGameIds}, 
            'LV': {'Name': 'Raiders', 'GameIds': RaidersGameIds}, 
            'CHI': {'Name': 'Bears', 'GameIds': BearsGameIds}, 
            'NYG': {'Name': 'Giants', 'GameIds': GiantsGameIds}, 
            'TEN': {'Name': 'Titans', 'GameIds': TitansGameIds}, 
            'BUF': {'Name': 'Bills', 'GameIds': BillsGameIds}, 
            'CAR': {'Name': 'Panthers', 'GameIds': PanthersGameIds}, 
            'DET': {'Name': 'Lions', 'GameIds': LionsGameIds}, 
            'HOU': {'Name': 'Texans', 'GameIds': TexansGameIds}, 
            'IND': {'Name': 'Colts', 'GameIds': ColtsGameIds}, 
            'WAS': {'Name': 'Commanders', 'GameIds': CommandersGameIds}, 
            'KC': {'Name': 'Chiefs', 'GameIds': ChiefsGameIds}, 
            'PHI': {'Name': 'Eagles', 'GameIds': EaglesGameIds}, 
            'NO': {'Name': 'Saints', 'GameIds': SaintsGameIds}, 
            'NYJ': {'Name': 'Jets', 'GameIds': JetsGameIds}, 
            'MIA': {'Name': 'Dolphins', 'GameIds': DolphinsGameIds}, 
            'CIN': {'Name': 'Bengals', 'GameIds': BengalsGameIds}, 
            'GB': {'Name': 'Packers', 'GameIds': PackersGameIds}, 
            'SF': {'Name': '49ers', 'GameIds': SanFranciscoGameIds}, 
            'DAL': {'Name': 'Cowboys', 'GameIds': CowboysGameIds}}
            
df = pd.DataFrame(teamAbbr)

# ***SCOUTING***
### Schema:
* gameId: Game identifier, unique (numeric)
* playId: Play identifier, not unique across games (numeric)
* nflId: Player identification number, unique across players (numeric)
* pff_role: The player's role on this play (text)
 * Possible values:
 > - Coverage: Defensive player. Player whose initial goal is to play man or zone coverage
 > - Pass: Offensive player. Player identified as the passer
 > - Pass block: Offensive player. Anyone fully blocking a defender from the QB, or anyone in a clear pass block stance
 > - Pass route: Offensive player. Any player not identified as a Pass Blocker or Passer
 > - Pass rush: Defensive player. Any player whose initial intent is to rush the passer
* pff_positionLinedUp: Position that the player was aligned at the snap of the ball on this play (text)
* pff_hit: If player is a defensive player, indicator for whether they are credited with recording a hit on this play (binary)
* pff_hurry: If player is a defensive player, indicator for whether they are credited with recording a hurry on this play (binary)
* pff_sack: If player is a defensive player, indicator for whether they are credited with recording a sack on this play (binary)
* pff_beatenByDefender: If player is a blocking offensive player, indicator for whether they are by a defender but was not charged for yielding a hit, hurry or sack (binary)
* pff_hitAllowed: If player is a blocking offensive player, indicator for whether they are responsible for a hit on the QB (binary)
* pff_hurryAllowed: If player is a blocking offensive player, indicator for whether they are responsible for a hurry on the QB (binary)
* pff_sackAllowed: If player is a blocking offensive player, indicator for whether they are responsible for a sack on the QB (binary)
* pff_nflIdBlockedPlayer: If player is a blocking offensive player, the nflId of the first defender the offensive player blocked (numeric)
* pff_blockType: If player is a blocking offensive player, the type of block that the offensive player is executing on the defender (text)
 * Possible values:
 > - BH: Backfield Help - A block from a player aligned in the backfield on which the blocker merely helps on a block rather than fully engaging his assignment. Usually seen when a blocker is clearing up a block or picking up a defender when he has broken through or been missed by another blocker
 > - CH: Chip Block - This is only to be used for players who chip a pass rusher when they release for their route
 > - CL: Second Level – A block made at the second level, this must be at least two yards across the line of scrimmage
 > - NB: No Block - If a blocker executes no block on a play but simply runs his path or takes his pass set then we will note him with one all blocking line with this block type
 > - PA: Play Action Pass Protection - A blocker pass protecting inline on a play action pass selling the play action by stepping in to show a run block before converting to pass protect
 > - PP: Pass Protection - A standard pass protection block from an inline blocker
 > - PR: Pocket Roll Block - This block type will be used any time the offense is executing a “rolling pocket” by which the entire offensive line moves with the QB’s rollout to stay in front of him but without ever taking a “conventional” pass set. There will be flexibility here to record the PR – Pocket Roll Block type in the same way as PA & RP block types in that individual matchups & responsibilities won’t always be obvious or necessary, so PR block types can be recorded by multiple blockers on an individual defender on the same play
 > - PT: Post Block - A post block by an offensive player in pass protection to control a defender for another blocker while clearly demonstrating that he is not, at least initially, trying to fully engage with the block
 > - PU: Backfield Pickup - A pass protection pick-up by a player aligned in the backfield
 > - SR: Set & Release - A blocker who sets to pass protect a defender before releasing. This block will cover both players releasing from a set to block for a screen as well as “hold ups” by tight ends before they leak into the flat
 > - SW: Switch Block - A blocker who passes off (or attempts to pass off) a defender. Most often used on stunts but can also be used for pass offs when pass rushers are slanting across the pocket or interior defenders are working to the edge to replace a dropping edge rusher, with an interior offensive lineman passing them out rather than staying with them
 > - UP: Pull Pass Protection - A blocker pulling in pass protection from an inline alignment to block a defender in pass protection
* pff_backFieldBlock:If player is a blocking offensive player, indicator for whether block occured in offensive backfield.

In [483]:
scouting = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/pffScoutingData.csv")

In [491]:
# print(scouting.info())

tampa_dal = scouting[scouting['gameId'] == 2021090900]

In [492]:
tampa_dal_off = tampa_dal[tampa_dal['pff_role'] == 'Pass Block'].copy()
tampa_dal_off.drop(columns=['pff_hurry', 'pff_hit', 'pff_sack'], inplace=True)

In [493]:
tampa_dal_off.head()

,gameId,playId,nflId,pff_role,pff_positionLinedUp,pff_beatenByDefender,pff_hitAllowed,pff_hurryAllowed,pff_sackAllowed,pff_nflIdBlockedPlayer,pff_blockType,pff_backFieldBlock
4,2021090900,97,40151,Pass Block,C,0.0,0.0,0.0,0.0,44955.0,SW,0.0
7,2021090900,97,42377,Pass Block,LT,0.0,0.0,1.0,0.0,42403.0,PP,0.0
9,2021090900,97,42404,Pass Block,LG,0.0,0.0,0.0,0.0,44955.0,PP,0.0
16,2021090900,97,46163,Pass Block,RG,0.0,0.0,1.0,0.0,53441.0,SW,0.0
18,2021090900,97,52421,Pass Block,RT,0.0,0.0,1.0,0.0,53441.0,PP,0.0

# ***Players***
### Schema:
* **nflId:** Player identification number, unique across players (numeric int64)
* **height:** Player height (text object)
* **weight:** Player weight (numeric int64)
* **birthDate:** Date of birth (YYYY-MM-DD object)
* **collegeName:** Player College (text object)
* **officialPosition:** Official player position (text object)
* **displayName:** Player Name (text object)

In [438]:
players = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/players.csv")

In [439]:
print(players.info())

players.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1679 entries, 0 to 1678
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nflId             1679 non-null   int64
 1   height            1679 non-null   object
 2   weight            1679 non-null   int64
 3   birthDate         1447 non-null   object
 4   collegeName       1455 non-null   object
 5   officialPosition  1679 non-null   object
 6   displayName       1679 non-null   object
dtypes: int64(2), object(5)
memory usage: 91.9+ KB
None

,nflId,height,weight,birthDate,collegeName,officialPosition,displayName
0,25511,6-4,225,1977-08-03,Michigan,QB,Tom Brady
1,28963,6-5,240,1982-03-02,"Miami, O.",QB,Ben Roethlisberger
2,29550,6-4,328,1982-01-22,Arkansas,T,Jason Peters
3,29851,6-2,225,1983-12-02,California,QB,Aaron Rodgers
4,30078,6-2,228,1982-11-24,Harvard,QB,Ryan Fitzpatrick

# ***PLAYS***
### Schema:
* gameId: Game identifier, unique (numeric)
* playId: Play identifier, not unique across games (numeric)
* playDescription: Description of play (text)
* quarter: Game quarter (numeric)
* down: Down (numeric)
* yardsToGo: Distance needed for a first down (numeric)
* possessionTeam: Team abbr of team on offense with possession of ball (text)
* defensiveTeam: Team abbr of team on defense (text)
* yardlineSide: 3-letter team code corresponding to line-of-scrimmage (text)
* yardlineNumber: Yard line at line-of-scrimmage (numeric)
* gameClock: Time on clock of play (MM:SS)
* preSnapHomeScore: Home score prior to the play (numeric)
* preSnapVisitorScore: Visiting team score prior to the play (numeric)
* passResult: Dropback outcome of the play (text)
 * C: Complete pass
 * I: Incomplete pass 
 * S: Quarterback sack 
 * IN: Intercepted pass 
 * R: Scramble
* penaltyYards: yards gained by offense by penalty (numeric)
* prePenaltyPlayResult: Net yards gained by the offense, before penalty yardage (numeric)
* playResult: Net yards gained by the offense, including penalty yardage (numeric)
* foulName[i]: Name of the i-th penalty committed during the play. i ranges between 1 and 3 (text)
* foulNFLId[i]: nflId of the player who comitted the i-th penalty during the play. i ranges between 1 and 3 (numeric)
* absoluteYardlineNumber: Distance from end zone for possession team (numeric)
* offenseFormation: Formation used by possession team (text)
* personnelO: Personnel used by offensive team (text)
* defendersInTheBox: Number of defenders in close proximity to line-of-scrimmage (numeric)
* personnelD: Personnel used by defensive team (text)
* dropbackType: Dropback categorization of quarterback (text)
* pff_playAction: indicator for whether offense executes play action fake on the play. Variable provided by PFF (binary)
* pff_passCoverage: Coverage scheme of defense. Variable provided by PFF (text)
 * Possible values:
 > - Cover-0: A Man to Man coverage across the board with no deep defenders. This coverage is typically accompanied with a blitz
 > - Cover-1: When a defense plays any form of Man defense across the board with a Defensive Player as a Single High Man concept
 > - Cover-2: A two deep safety concept where any zone principle is applied
 > - 2-Man: A two deep safety concept where a man principle is applied
 > - Cover-3: Any 3 Deep, 4 Under concept
 > - Quarters: A Quarters concept on both halves of the field. In general it will be a 4 Deep, 3 Under concept where the corners are on #1, safeties on #2, and backside safety rotation dependent on formation
 > - Cover-6: A Quarters Concept on half the field and a 2 Deep concept on the other half
 > - Bracket: Recorded in the field and up to the 12 yard line in the red zone – when two offensive players have an in and out bracket by two defenders
 > - Goal Line: Calls where a Goal Line defense is used.
 > - Red Zone: Calls that are typically specific to the Red Zone and do not occur in the field often
 > - Prevent: Special end of half or end of game situations where a Prevent defense is utilized
 > - Miscellaneous: Coverage concepts that we feel do not comfortably fit into any of our coverage categories
* pff_passCoverageType: Whether defense's coverage type was man, zone or other. Variable provided by PFF (text)

In [440]:
plays = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/plays.csv")

In [441]:
print(plays.info())

plays.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8557 entries, 0 to 8556
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gameId                  8557 non-null   int64
 1   playId                  8557 non-null   int64
 2   playDescription         8557 non-null   object
 3   quarter                 8557 non-null   int64
 4   down                    8557 non-null   int64
 5   yardsToGo               8557 non-null   int64
 6   possessionTeam          8557 non-null   object
 7   defensiveTeam           8557 non-null   object
 8   yardlineSide            8432 non-null   object
 9   yardlineNumber          8557 non-null   int64
 10  gameClock               8557 non-null   object
 11  preSnapHomeScore        8557 non-null   int64
 12  preSnapVisitorScore     8557 non-null   int64
 13  passResult              8557 non-null   object
 14  penaltyYards            756 non-null    float64
 15  prePenaltyPlayResult    8557 non-null   int64
 16  playResult              8557 non-null   int64
 17  foulName1               736 non-null    object
 18  foulNFLId1              736 non-null    float64
 19  foulName2               30 non-null     object
 20  foulNFLId2              30 non-null     float64
 21  foulName3               1 non-null      object
 22  foulNFLId3              1 non-null      float64
 23  absoluteYardlineNumber  8556 non-null   float64
 24  offenseFormation        8550 non-null   object
 25  personnelO              8556 non-null   object
 26  defendersInBox          8550 non-null   float64
 27  personnelD              8556 non-null   object
 28  dropBackType            8029 non-null   object
 29  pff_playAction          8557 non-null   int64
 30  pff_passCoverage        8557 non-null   object
 31  pff_passCoverageType    8557 non-null   object
dtypes: float64(6), int64(11), object(15)
memory usage: 2.1+ MB
None

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineSide,yardlineNumber,gameClock,preSnapHomeScore,preSnapVisitorScore,passResult,penaltyYards,prePenaltyPlayResult,playResult,foulName1,foulNFLId1,foulName2,foulNFLId2,foulName3,foulNFLId3,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,2021090900,97,(13:33) (Shotgun) T.Brady pass incomplete deep right to C.Godwin.,1,3,2,TB,DAL,TB,33,13:33,0,0,I,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,43.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
1,2021090900,137,(13:18) (Shotgun) D.Prescott pass deep left to A.Cooper pushed ob at DAL 30 for 28 yards (A.Winfield).,1,1,10,DAL,TB,DAL,2,13:18,0,0,C,NaN,28,28,NaN,NaN,NaN,NaN,NaN,NaN,108.0,EMPTY,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 4 LB, 3 DB",TRADITIONAL,0,Cover-3,Zone
2,2021090900,187,(12:23) (Shotgun) D.Prescott pass short middle to D.Schultz to DAL 39 for 5 yards (D.White).,1,2,6,DAL,TB,DAL,34,12:23,0,0,C,NaN,5,5,NaN,NaN,NaN,NaN,NaN,NaN,76.0,SHOTGUN,"0 RB, 2 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
3,2021090900,282,(9:56) D.Prescott pass incomplete deep left to C.Lamb.,1,1,10,DAL,TB,TB,39,09:56,0,0,I,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,49.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
4,2021090900,349,(9:46) (Shotgun) D.Prescott pass incomplete short left to C.Lamb [L.David].,1,3,15,DAL,TB,TB,44,09:46,0,0,I,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,54.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone

# ***TRACKING DATA***
## Schema: 
* gameId: Game identifier, unique (numeric)
* playId: Play identifier, not unique across games (numeric)
* nflId: Player identification number, unique across players. When value is NA, row corresponds to ball. (numeric)
* frameId: Frame identifier for each play, starting at 1 (numeric)
* time: Time stamp of play (time, yyyy-mm-dd, hh:mm:ss)
* jerseyNumber: Jersey number of player (numeric)
* club: Team abbrevation of corresponding player (text)
* playDirection: Direction that the offense is moving (left or right)
* x: Player position along the long axis of the field, 0 - 120 yards. See Figure 1 below. (numeric)
* y: Player position along the short axis of the field, 0 - 53.3 yards. See Figure 1 below. (numeric)
* s: Speed in yards/second (numeric)
* a: Acceleration in yards/second^2 (numeric)
* dis: Distance traveled from prior time point, in yards (numeric)
* o: Player orientation (deg), 0 - 360 degrees (numeric)
* dir: Angle of player motion (deg), 0 - 360 degrees (numeric)
* event: Tagged play details, including moment of ball snap, pass release, pass catch, tackle, etc (text)

## Week 1

In [442]:
week1 = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/week1.csv")

In [443]:
print(week1.info())
week1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1118122 entries, 0 to 1118121
Data columns (total 16 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   gameId         1118122 non-null  int64
 1   playId         1118122 non-null  int64
 2   nflId          1069508 non-null  float64
 3   frameId        1118122 non-null  int64
 4   time           1118122 non-null  object
 5   jerseyNumber   1069508 non-null  float64
 6   team           1118122 non-null  object
 7   playDirection  1118122 non-null  object
 8   x              1118122 non-null  float64
 9   y              1118122 non-null  float64
 10  s              1118122 non-null  float64
 11  a              1118122 non-null  float64
 12  dis            1118122 non-null  float64
 13  o              1069508 non-null  float64
 14  dir            1069508 non-null  float64
 15  event          1118122 non-null  object
dtypes: float64(9), int64(3), object(4)
memory usage: 136.5+ MB
None

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021090900,97,25511.0,1,2021-09-10T00:26:31.100,12.0,TB,right,37.77,24.22,0.29,0.30,0.03,165.16,84.99,None
1,2021090900,97,25511.0,2,2021-09-10T00:26:31.200,12.0,TB,right,37.78,24.22,0.23,0.11,0.02,164.33,92.87,None
2,2021090900,97,25511.0,3,2021-09-10T00:26:31.300,12.0,TB,right,37.78,24.24,0.16,0.10,0.01,160.24,68.55,None
3,2021090900,97,25511.0,4,2021-09-10T00:26:31.400,12.0,TB,right,37.73,24.25,0.15,0.24,0.06,152.13,296.85,None
4,2021090900,97,25511.0,5,2021-09-10T00:26:31.500,12.0,TB,right,37.69,24.26,0.25,0.18,0.04,148.33,287.55,None

Buccaneers vs. Cowboys (week 1, plays dataset)
* 2021090900

In [444]:
plays.drop(columns=['yardlineSide', 'preSnapHomeScore',
                    'foulName1', 'foulNFLId1',	'foulName2',	
                    'foulNFLId2',	'foulName3', 'foulNFLId3',
                    'penaltyYards', 'prePenaltyPlayResult'], inplace=True)

In [445]:
TB_DAL_tracking = week1[week1['gameId'] == 2021090900]

# TB_DAL_tracking

In [446]:
TB_DAL_plays = plays[plays['gameId'] == 2021090900]

TB_DAL_plays.sort_values(by=['possessionTeam', 'quarter', 'gameClock'], ascending=[True, True, False])

TB_DAL_plays

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineNumber,gameClock,preSnapVisitorScore,passResult,playResult,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
0,2021090900,97,(13:33) (Shotgun) T.Brady pass incomplete deep right to C.Godwin.,1,3,2,TB,DAL,33,13:33,0,I,0,43.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
1,2021090900,137,(13:18) (Shotgun) D.Prescott pass deep left to A.Cooper pushed ob at DAL 30 for 28 yards (A.Winfield).,1,1,10,DAL,TB,2,13:18,0,C,28,108.0,EMPTY,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 4 LB, 3 DB",TRADITIONAL,0,Cover-3,Zone
2,2021090900,187,(12:23) (Shotgun) D.Prescott pass short middle to D.Schultz to DAL 39 for 5 yards (D.White).,1,2,6,DAL,TB,34,12:23,0,C,5,76.0,SHOTGUN,"0 RB, 2 TE, 3 WR",6.0,"3 DL, 3 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
3,2021090900,282,(9:56) D.Prescott pass incomplete deep left to C.Lamb.,1,1,10,DAL,TB,39,09:56,0,I,0,49.0,SINGLEBACK,"1 RB, 2 TE, 2 WR",6.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-3,Zone
4,2021090900,349,(9:46) (Shotgun) D.Prescott pass incomplete short left to C.Lamb [L.David].,1,3,15,DAL,TB,44,09:46,0,I,0,54.0,SHOTGUN,"1 RB, 1 TE, 3 WR",7.0,"3 DL, 4 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,2021090900,4677,"(:30) (No Huddle, Shotgun) T.Brady pass incomplete deep right to A.Brown.",4,1,10,TB,DAL,42,00:30,29,I,0,68.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
93,2021090900,4699,(:24) (Shotgun) T.Brady pass deep left to C.Godwin ran ob at DAL 18 for 24 yards.,4,2,10,TB,DAL,42,00:24,29,C,24,68.0,SHOTGUN,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
94,2021090900,4728,(:18) (Shotgun) T.Brady pass incomplete short left.,4,1,10,TB,DAL,18,00:18,29,I,0,92.0,SHOTGUN,"1 RB, 0 TE, 4 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,2-Man,Man
95,2021090900,4750,(:14) (Shotgun) T.Brady pass incomplete short left.,4,2,10,TB,DAL,18,00:14,29,I,0,92.0,EMPTY,"1 RB, 1 TE, 3 WR",5.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,2-Man,Man
96,2021090900,4772,(:10) (Shotgun) T.Brady pass incomplete short left.,4,3,10,TB,DAL,18,00:10,29,I,0,92.0,EMPTY,"1 RB, 1 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-0,Man

Falcons vs. Eagles

In [447]:
ATL_PHI = plays[plays['gameId'] == 2021091200]
ATL_PHI

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineNumber,gameClock,preSnapVisitorScore,passResult,playResult,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
97,2021091200,56,(15:00) M.Ryan pass deep middle to C.Ridley to ATL 41 for 16 yards (D.Slay; M.Epps).,1,1,10,ATL,PHI,25,15:00,0,C,16,35.0,I_FORM,"2 RB, 2 TE, 1 WR",7.0,"4 DL, 3 LB, 4 DB",TRADITIONAL,1,Cover-2,Zone
98,2021091200,122,(13:45) (No Huddle) M.Ryan pass short right to C.Patterson to PHI 42 for 1 yard (D.Slay; A.Singleton).,1,2,6,ATL,PHI,43,13:45,0,C,1,67.0,SINGLEBACK,"2 RB, 2 TE, 1 WR",6.0,"4 DL, 2 LB, 5 DB",DESIGNED_ROLLOUT_RIGHT,1,Cover-2,Zone
99,2021091200,146,"(13:08) (No Huddle, Shotgun) M.Ryan pass short right to C.Ridley pushed ob at PHI 31 for 11 yards (A.Harris).",1,3,5,ATL,PHI,42,13:08,0,C,11,68.0,EMPTY,"2 RB, 2 TE, 1 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
100,2021091200,176,(12:50) (No Huddle) M.Ryan pass incomplete short right to K.Pitts.,1,1,10,ATL,PHI,31,12:50,0,I,0,79.0,SINGLEBACK,"2 RB, 2 TE, 1 WR",7.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,1,Cover-3,Zone
101,2021091200,231,(12:08) (Shotgun) M.Ryan pass short middle to C.Ridley to PHI 16 for 12 yards (M.Epps) [J.Hargrave].,1,3,7,ATL,PHI,28,12:08,0,C,12,82.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-3,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,2021091200,4274,(4:13) (Shotgun) M.Ryan pass short right to K.Pitts to ATL 49 for 5 yards (A.Maddox).,4,1,10,ATL,PHI,44,04:13,29,C,5,66.0,SHOTGUN,"1 RB, 2 TE, 2 WR",5.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-6,Zone
166,2021091200,4298,"(3:50) (No Huddle, Shotgun) M.Ryan sacked at ATL 41 for -8 yards (H.Ridgeway).",4,2,5,ATL,PHI,49,03:50,29,S,-8,61.0,SHOTGUN,"1 RB, 2 TE, 2 WR",4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Quarters,Zone
167,2021091200,4317,"(3:24) (No Huddle, Shotgun) M.Ryan pass incomplete short right to R.Gage.",4,3,13,ATL,PHI,41,03:24,29,I,0,69.0,SHOTGUN,"1 RB, 2 TE, 2 WR",4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Quarters,Zone
168,2021091200,4346,(3:19) (Shotgun) M.Ryan sacked at ATL 31 for -10 yards (J.Hargrave).,4,4,13,ATL,PHI,41,03:19,29,S,-10,69.0,SHOTGUN,"1 RB, 2 TE, 2 WR",4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Quarters,Zone
169,2021091200,4367,(6:13) (Shotgun) M.Ryan pass short left to C.Ridley pushed ob at ATL 32 for 7 yards (A.Maddox).,4,3,17,ATL,PHI,25,06:13,22,C,7,85.0,SHOTGUN,"1 RB, 1 TE, 3 WR",4.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Quarters,Zone

BILLS vs. STEELERS
* 2021091201

In [448]:
bills_steelers = plays[plays['gameId'] == 2021091201]
bills_steelers

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineNumber,gameClock,preSnapVisitorScore,passResult,playResult,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
170,2021091201,63,"(14:47) (Shotgun) J.Allen pass short right to C.Beasley to PIT 17 for 7 yards (T.Norwood, D.Bush).",1,1,10,BUF,PIT,24,14:47,0,C,7,34.0,EMPTY,"0 RB, 0 TE, 5 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Quarters,Zone
171,2021091201,111,"(13:40) (No Huddle, Shotgun) J.Allen pass incomplete short left to S.Diggs (C.Heyward). Pass tipped at line.",1,3,5,BUF,PIT,19,13:40,0,I,0,29.0,SHOTGUN,"0 RB, 0 TE, 5 WR",4.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
172,2021091201,262,(10:47) (Shotgun) B.Roethlisberger pass incomplete short right to D.Johnson.,1,3,4,PIT,BUF,47,10:47,0,I,0,57.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
173,2021091201,345,"(9:28) (No Huddle, Shotgun) J.Allen scrambles left end ran ob at BUF 35 for 13 yards (T.Norwood). PENALTY on BUF-D.Dawkins, Offensive Holding, 10 yards, enforced at BUF 22 - No Play.",1,1,10,BUF,PIT,22,09:28,0,R,-10,88.0,EMPTY,"1 RB, 1 TE, 3 WR",4.0,"2 DL, 4 LB, 5 DB",NaN,0,Cover-1,Man
174,2021091201,406,"(8:24) (Shotgun) J.Allen pass short left to C.Beasley to BUF 23 for 5 yards (T.Norwood, D.Bush).",1,2,14,BUF,PIT,18,08:24,0,C,5,92.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"2 DL, 4 LB, 5 DB",TRADITIONAL,1,Cover-2,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,2021091201,4156,"(1:47) (Shotgun) J.Allen pass short middle to C.Beasley to PIT 37 for 10 yards (T.Norwood, M.Fitzpatrick).",4,2,20,BUF,PIT,47,01:47,23,C,10,63.0,SHOTGUN,"1 RB, 0 TE, 4 WR",4.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-3,Zone
247,2021091201,4180,"(1:27) (No Huddle, Shotgun) J.Allen pass short left to S.Diggs pushed ob at PIT 24 for 13 yards (J.Pierre).",4,3,10,BUF,PIT,37,01:27,23,C,13,73.0,SHOTGUN,"1 RB, 0 TE, 4 WR",5.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-3,Zone
248,2021091201,4209,"(1:20) (No Huddle, Shotgun) J.Allen pass short left to D.Singletary to PIT 19 for 5 yards (D.Bush). FUMBLES (D.Bush), ball out of bounds at PIT 19.",4,1,10,BUF,PIT,24,01:20,23,C,5,86.0,EMPTY,"1 RB, 0 TE, 4 WR",5.0,"2 DL, 3 LB, 6 DB",TRADITIONAL,0,Cover-3,Zone
249,2021091201,4233,"(:59) (No Huddle, Shotgun) J.Allen pass incomplete deep right to C.Beasley [M.Ingram]. PENALTY on PIT-M.Ingram, Defensive Offside, 5 yards, enforced at PIT 19 - No Play.",4,2,5,BUF,PIT,19,00:59,23,I,5,91.0,EMPTY,"1 RB, 0 TE, 4 WR",3.0,"2 DL, 3 LB, 6 DB",NaN,0,Cover-3,Zone
250,2021091201,4266,"(:54) (Shotgun) J.Allen pass incomplete short middle to E.Sanders (T.Norwood). PENALTY on BUF-Da.Williams, Offensive Holding, 10 yards, enforced at PIT 14 - No Play.",4,1,10,BUF,PIT,14,00:54,23,I,-10,96.0,EMPTY,"1 RB, 0 TE, 4 WR",3.0,"2 DL, 3 LB, 6 DB",NaN,0,Cover-3,Zone

PANTHERS VS JETS 
* 2021091202

In [449]:
panthers_jets = plays[plays['gameId'] == 2021091202]

BENGALS VS. VIKINGS 
* 2021091203

In [450]:
bengals_vikings = plays[plays['gameId'] == 2021091203]
bengals_vikings

,gameId,playId,playDescription,quarter,down,yardsToGo,possessionTeam,defensiveTeam,yardlineNumber,gameClock,preSnapVisitorScore,passResult,playResult,absoluteYardlineNumber,offenseFormation,personnelO,defendersInBox,personnelD,dropBackType,pff_playAction,pff_passCoverage,pff_passCoverageType
323,2021091203,125,(14:10) K.Cousins pass short middle to T.Conklin to MIN 30 for 6 yards (G.Pratt).,1,2,11,MIN,CIN,24,14:10,0,C,6,34.0,SINGLEBACK,"2 RB, 1 TE, 2 WR",7.0,"5 DL, 2 LB, 4 DB",TRADITIONAL,0,Cover-3,Zone
324,2021091203,149,(13:33) (Shotgun) K.Cousins pass short left to A.Thielen pushed ob at MIN 42 for 12 yards (M.Hilton).,1,3,5,MIN,CIN,30,13:33,0,C,12,40.0,EMPTY,"0 RB, 1 TE, 4 WR",5.0,"4 DL, 1 LB, 6 DB",TRADITIONAL,0,Cover-1,Man
325,2021091203,223,"(12:16) K.Cousins pass short middle to A.Thielen to MIN 42 for 4 yards (L.Wilson) [L.Ogunjobi]. PENALTY on MIN-O.Udoh, Offensive Holding, 10 yards, enforced at MIN 38 - No Play.",1,2,14,MIN,CIN,38,12:16,0,C,-10,48.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",NaN,0,Cover-3,Zone
326,2021091203,258,(11:49) (Shotgun) K.Cousins pass incomplete short left to J.Jefferson.,1,2,24,MIN,CIN,28,11:49,0,I,0,38.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-2,Zone
327,2021091203,280,(11:44) (Shotgun) K.Cousins pass short middle to D.Westbrook to MIN 39 for 11 yards (R.Allen; J.Bates).,1,3,24,MIN,CIN,28,11:44,0,C,11,38.0,SHOTGUN,"1 RB, 0 TE, 4 WR",5.0,"3 DL, 2 LB, 6 DB",TRADITIONAL,0,Cover-3,Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,2021091203,4528,(3:57) (Shotgun) J.Burrow pass incomplete short middle to J.Chase.,5,3,6,CIN,MIN,14,03:57,24,I,0,24.0,SHOTGUN,"1 RB, 1 TE, 3 WR",6.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-6,Zone
395,2021091203,4596,"(3:05) K.Cousins pass incomplete short right to J.Jefferson [S.Hubbard]. PENALTY on CIN-C.Awuzie, Defensive Holding, 5 yards, enforced at MIN 37 - No Play.",5,2,10,MIN,CIN,37,03:05,24,I,5,73.0,SINGLEBACK,"1 RB, 1 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",NaN,1,Cover-1,Man
396,2021091203,4629,(3:00) K.Cousins pass short right to C.Ham ran ob at MIN 45 for 3 yards.,5,1,10,MIN,CIN,42,03:00,24,C,3,68.0,SINGLEBACK,"2 RB, 0 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",DESIGNED_ROLLOUT_RIGHT,1,Cover-3,Zone
397,2021091203,4682,(2:18) (Shotgun) K.Cousins pass short middle to J.Jefferson to CIN 38 for 12 yards (C.Awuzie).,5,3,2,MIN,CIN,50,02:18,24,C,12,60.0,EMPTY,"1 RB, 1 TE, 3 WR",7.0,"4 DL, 2 LB, 5 DB",TRADITIONAL,0,Cover-1,Man
398,2021091203,4849,(:39) J.Burrow pass short left to C.Uzomah pushed ob at MIN 20 for 32 yards (X.Woods).,5,4,1,CIN,MIN,48,00:39,24,C,32,58.0,JUMBO,"1 RB, 3 TE, 1 WR",9.0,"5 DL, 2 LB, 4 DB",TRADITIONAL,1,Cover-0,Man

LIONS VS. 49ERS
* 2021091204

In [451]:
lions_49ers = plays[plays['gameId'] == 2021091204]

TEXANS VS. JAGUARS
* 2021091205

In [452]:
texans_jags = plays[plays['gameId'] == 2021091205]

COLTS VS SEAHAWKS
* 2021091206

In [453]:
colts_seahawks = plays[plays['gameId'] == 2021091206]

TITANS VS. CARDINALS
* 2021091207

In [454]:
titans_cardinals = plays[plays['gameId'] == 2021091207]

COMMANDERS VS. CHARGERS
* 2021091208

In [455]:
commanders_chargers = plays[plays['gameId'] == 2021091208]

CHIEFS VS. BROWNS
* 2021091209

In [456]:
chiefs_browns = plays[plays['gameId'] == 2021091209]

PATRIOTS VS. DOLPHINS
* 2021091210

In [457]:
pats_dolphins = plays[plays['gameId'] == 2021091210]

SAINTS VS PACKERS
* 2021091211

In [458]:
saints_packers = plays[plays['gameId'] == 2021091211]

GIANTS VS BRONCOS
* 2021091212

In [459]:
giants_broncos = plays[plays['gameId'] == 2021091212]

RAMS VS. BEARS
* 2021091213

In [460]:
rams_bears = plays[plays['gameId'] == 2021091213]

RAIDERS VS. RAVENS
* 2021091300

In [461]:
raiders_ravens = plays[plays['gameId'] == 2021091300]

## ***WEEK 2***

In [462]:
week2 = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/week2.csv")

In [463]:
print(week2.info())
week2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1042774 entries, 0 to 1042773
Data columns (total 16 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   gameId         1042774 non-null  int64
 1   playId         1042774 non-null  int64
 2   nflId          997436 non-null   float64
 3   frameId        1042774 non-null  int64
 4   time           1042774 non-null  object
 5   jerseyNumber   997436 non-null   float64
 6   team           1042774 non-null  object
 7   playDirection  1042774 non-null  object
 8   x              1042774 non-null  float64
 9   y              1042774 non-null  float64
 10  s              1042774 non-null  float64
 11  a              1042774 non-null  float64
 12  dis            1042774 non-null  float64
 13  o              997436 non-null   float64
 14  dir            997436 non-null   float64
 15  event          1042774 non-null  object
dtypes: float64(9), int64(3), object(4)
memory usage: 127.3+ MB
None

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021091600,65,40031.0,1,2021-09-17T00:23:09.600,23.0,NYG,right,46.32,22.36,0.93,0.83,0.09,271.71,79.32,None
1,2021091600,65,40031.0,2,2021-09-17T00:23:09.700,23.0,NYG,right,46.43,22.39,1.07,1.05,0.11,275.92,72.33,None
2,2021091600,65,40031.0,3,2021-09-17T00:23:09.800,23.0,NYG,right,46.54,22.44,1.21,1.11,0.12,278.85,67.03,None
3,2021091600,65,40031.0,4,2021-09-17T00:23:09.900,23.0,NYG,right,46.65,22.49,1.32,1.14,0.13,282.45,62.63,None
4,2021091600,65,40031.0,5,2021-09-17T00:23:10.000,23.0,NYG,right,46.77,22.56,1.49,1.42,0.14,285.54,59.26,None

## ***WEEK 3***

In [464]:
week3 = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/week3.csv")

In [465]:
print(week3.info())
week3.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1121825 entries, 0 to 1121824
Data columns (total 16 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   gameId         1121825 non-null  int64
 1   playId         1121825 non-null  int64
 2   nflId          1073050 non-null  float64
 3   frameId        1121825 non-null  int64
 4   time           1121825 non-null  object
 5   jerseyNumber   1073050 non-null  float64
 6   team           1121825 non-null  object
 7   playDirection  1121825 non-null  object
 8   x              1121825 non-null  float64
 9   y              1121825 non-null  float64
 10  s              1121825 non-null  float64
 11  a              1121825 non-null  float64
 12  dis            1121825 non-null  float64
 13  o              1073050 non-null  float64
 14  dir            1073050 non-null  float64
 15  event          1121825 non-null  object
dtypes: float64(9), int64(3), object(4)
memory usage: 136.9+ MB
None

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021092300,54,41300.0,1,2021-09-24T00:23:08.400,58.0,HOU,right,38.66,28.98,0.00,0.00,0.00,259.88,205.34,None
1,2021092300,54,41300.0,2,2021-09-24T00:23:08.500,58.0,HOU,right,38.66,28.98,0.00,0.00,0.01,259.88,197.10,None
2,2021092300,54,41300.0,3,2021-09-24T00:23:08.600,58.0,HOU,right,38.66,28.97,0.00,0.00,0.00,259.88,192.98,None
3,2021092300,54,41300.0,4,2021-09-24T00:23:08.700,58.0,HOU,right,38.66,28.97,0.02,0.34,0.00,259.88,181.68,None
4,2021092300,54,41300.0,5,2021-09-24T00:23:08.800,58.0,HOU,right,38.66,28.97,0.05,0.37,0.00,260.78,199.16,None

## ***WEEK 4***

In [466]:
week4 = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/week4.csv")

In [467]:
print(week4.info())
week4.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1074606 entries, 0 to 1074605
Data columns (total 16 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   gameId         1074606 non-null  int64
 1   playId         1074606 non-null  int64
 2   nflId          1027884 non-null  float64
 3   frameId        1074606 non-null  int64
 4   time           1074606 non-null  object
 5   jerseyNumber   1027884 non-null  float64
 6   team           1074606 non-null  object
 7   playDirection  1074606 non-null  object
 8   x              1074606 non-null  float64
 9   y              1074606 non-null  float64
 10  s              1074606 non-null  float64
 11  a              1074606 non-null  float64
 12  dis            1074606 non-null  float64
 13  o              1027884 non-null  float64
 14  dir            1027884 non-null  float64
 15  event          1074606 non-null  object
dtypes: float64(9), int64(3), object(4)
memory usage: 131.2+ MB
None

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021093000,169,38696.0,1,2021-10-01T00:29:42.800,11.0,JAX,right,54.66,44.66,0.0,0.0,0.0,107.61,134.74,None
1,2021093000,169,38696.0,2,2021-10-01T00:29:42.900,11.0,JAX,right,54.66,44.66,0.0,0.0,0.0,107.61,130.79,None
2,2021093000,169,38696.0,3,2021-10-01T00:29:43.000,11.0,JAX,right,54.66,44.67,0.0,0.0,0.0,107.61,122.78,None
3,2021093000,169,38696.0,4,2021-10-01T00:29:43.100,11.0,JAX,right,54.66,44.66,0.0,0.0,0.0,107.61,134.78,None
4,2021093000,169,38696.0,5,2021-10-01T00:29:43.200,11.0,JAX,right,54.66,44.66,0.0,0.0,0.0,107.61,130.76,None

## ***WEEK 5***

In [468]:
week5 = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/week5.csv")

In [469]:
print(week5.info())
week5.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1097813 entries, 0 to 1097812
Data columns (total 16 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   gameId         1097813 non-null  int64
 1   playId         1097813 non-null  int64
 2   nflId          1050082 non-null  float64
 3   frameId        1097813 non-null  int64
 4   time           1097813 non-null  object
 5   jerseyNumber   1050082 non-null  float64
 6   team           1097813 non-null  object
 7   playDirection  1097813 non-null  object
 8   x              1097813 non-null  float64
 9   y              1097813 non-null  float64
 10  s              1097813 non-null  float64
 11  a              1097813 non-null  float64
 12  dis            1097813 non-null  float64
 13  o              1050082 non-null  float64
 14  dir            1050082 non-null  float64
 15  event          1097813 non-null  object
dtypes: float64(9), int64(3), object(4)
memory usage: 134.0+ MB
None

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021100700,95,30869.0,1,2021-10-08T00:23:33.900,77.0,LA,right,22.93,33.04,0.02,0.02,0.00,102.26,129.51,None
1,2021100700,95,30869.0,2,2021-10-08T00:23:34.000,77.0,LA,right,22.93,33.04,0.01,0.02,0.00,101.64,128.68,None
2,2021100700,95,30869.0,3,2021-10-08T00:23:34.100,77.0,LA,right,22.92,33.05,0.01,0.01,0.01,100.73,127.26,None
3,2021100700,95,30869.0,4,2021-10-08T00:23:34.200,77.0,LA,right,22.92,33.05,0.01,0.01,0.01,100.73,130.90,None
4,2021100700,95,30869.0,5,2021-10-08T00:23:34.300,77.0,LA,right,22.91,33.05,0.01,0.01,0.01,99.55,134.16,None

## ***WEEK 6***

In [470]:
week6 = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/week6.csv")

In [471]:
print(week6.info())
week6.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973797 entries, 0 to 973796
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   gameId         973797 non-null  int64
 1   playId         973797 non-null  int64
 2   nflId          931458 non-null  float64
 3   frameId        973797 non-null  int64
 4   time           973797 non-null  object
 5   jerseyNumber   931458 non-null  float64
 6   team           973797 non-null  object
 7   playDirection  973797 non-null  object
 8   x              973797 non-null  float64
 9   y              973797 non-null  float64
 10  s              973797 non-null  float64
 11  a              973797 non-null  float64
 12  dis            973797 non-null  float64
 13  o              931458 non-null  float64
 14  dir            931458 non-null  float64
 15  event          973797 non-null  object
dtypes: float64(9), int64(3), object(4)
memory usage: 118.9+ MB
None

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021101400,76,25511.0,1,2021-10-15T00:23:39.200,12.0,TB,right,33.99,23.88,0.0,0.0,0.00,91.73,67.89,None
1,2021101400,76,25511.0,2,2021-10-15T00:23:39.300,12.0,TB,right,33.99,23.88,0.0,0.0,0.00,91.73,57.67,None
2,2021101400,76,25511.0,3,2021-10-15T00:23:39.400,12.0,TB,right,34.00,23.89,0.0,0.0,0.01,91.73,49.03,None
3,2021101400,76,25511.0,4,2021-10-15T00:23:39.500,12.0,TB,right,34.00,23.89,0.0,0.0,0.00,91.73,47.57,None
4,2021101400,76,25511.0,5,2021-10-15T00:23:39.600,12.0,TB,right,34.00,23.89,0.0,0.0,0.00,91.73,50.68,None

## ***WEEK 7***

In [472]:
week7 = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/week7.csv")

In [473]:
print(week7.info())
week7.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 906292 entries, 0 to 906291
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   gameId         906292 non-null  int64
 1   playId         906292 non-null  int64
 2   nflId          866888 non-null  float64
 3   frameId        906292 non-null  int64
 4   time           906292 non-null  object
 5   jerseyNumber   866888 non-null  float64
 6   team           906292 non-null  object
 7   playDirection  906292 non-null  object
 8   x              906292 non-null  float64
 9   y              906292 non-null  float64
 10  s              906292 non-null  float64
 11  a              906292 non-null  float64
 12  dis            906292 non-null  float64
 13  o              866888 non-null  float64
 14  dir            866888 non-null  float64
 15  event          906292 non-null  object
dtypes: float64(9), int64(3), object(4)
memory usage: 110.6+ MB
None

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021102100,56,35459.0,1,2021-10-22T00:23:17.300,22.0,DEN,left,75.42,20.77,0.97,1.03,0.09,60.75,64.69,None
1,2021102100,56,35459.0,2,2021-10-22T00:23:17.400,22.0,DEN,left,75.51,20.82,1.09,0.97,0.11,63.06,60.90,None
2,2021102100,56,35459.0,3,2021-10-22T00:23:17.500,22.0,DEN,left,75.61,20.88,1.23,0.79,0.12,63.06,61.13,None
3,2021102100,56,35459.0,4,2021-10-22T00:23:17.600,22.0,DEN,left,75.73,20.94,1.30,0.57,0.13,62.35,60.85,None
4,2021102100,56,35459.0,5,2021-10-22T00:23:17.700,22.0,DEN,left,75.84,21.01,1.33,0.37,0.13,60.65,60.99,None

## ***WEEK 8***

In [474]:
week8 = pd.read_csv("/content/drive/MyDrive/KAGGLE_NFL_COMPETITION/nfl-big-data-bowl-2023/week8.csv")

In [475]:
print(week8.info())
week8.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 978949 entries, 0 to 978948
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   gameId         978949 non-null  int64
 1   playId         978949 non-null  int64
 2   nflId          936386 non-null  float64
 3   frameId        978949 non-null  int64
 4   time           978949 non-null  object
 5   jerseyNumber   936386 non-null  float64
 6   team           978949 non-null  object
 7   playDirection  978949 non-null  object
 8   x              978949 non-null  float64
 9   y              978949 non-null  float64
 10  s              978949 non-null  float64
 11  a              978949 non-null  float64
 12  dis            978949 non-null  float64
 13  o              936386 non-null  float64
 14  dir            936386 non-null  float64
 15  event          978949 non-null  object
dtypes: float64(9), int64(3), object(4)
memory usage: 119.5+ MB
None

,gameId,playId,nflId,frameId,time,jerseyNumber,team,playDirection,x,y,s,a,dis,o,dir,event
0,2021102800,189,37077.0,1,2021-10-29T00:27:23.000,18.0,ARI,right,21.38,6.94,0.0,0.0,0.00,43.74,223.19,None
1,2021102800,189,37077.0,2,2021-10-29T00:27:23.100,18.0,ARI,right,21.38,6.94,0.0,0.0,0.00,44.67,243.81,None
2,2021102800,189,37077.0,3,2021-10-29T00:27:23.200,18.0,ARI,right,21.38,6.95,0.0,0.0,0.00,45.69,303.24,None
3,2021102800,189,37077.0,4,2021-10-29T00:27:23.300,18.0,ARI,right,21.38,6.94,0.0,0.0,0.00,46.44,285.89,None
4,2021102800,189,37077.0,5,2021-10-29T00:27:23.400,18.0,ARI,right,21.38,6.95,0.0,0.0,0.01,47.99,341.60,None



---



---



---



---



---



---