<a href="https://colab.research.google.com/github/stevenhastings/NFL_openCV/blob/main/Non_Video_Data_imports.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
import pandas as pd

In [81]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [82]:
pd.set_option('display.max_columns', 1000)

In [83]:
nfl = pd.read_csv("/content/drive/MyDrive/NFL_DATA/NFL Play by Play 2009-2018 (v5).csv/NFL Play by Play 2009-2018 (v5).csv",
                  parse_dates=['game_date'])

nfl.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (42,166,167,168,169,174,175,178,179,182,183,188,189,190,191,194,195,203,204,205,218,219,220,231,232,233,238,240,241,249) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,home_timeouts_remaining,away_timeouts_remaining,timeout,timeout_team,td_team,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa,wp,def_wp,home_wp,away_wp,wpa,home_wp_post,away_wp_post,total_home_rush_wpa,total_away_rush_wpa,total_home_pass_wpa,total_away_pass_wpa,air_wpa,yac_wpa,comp_air_wpa,comp_yac_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passer_player_id,passer_player_name,receiver_player_id,receiver_player_name,rusher_player_id,rusher_player_name,lateral_receiver_player_id,lateral_receiver_player_name,lateral_rusher_player_id,lateral_rusher_player_name,lateral_sack_player_id,lateral_sack_player_name,interception_player_id,interception_player_name,lateral_interception_player_id,lateral_interception_player_name,punt_returner_player_id,punt_returner_player_name,lateral_punt_returner_player_id,lateral_punt_returner_player_name,kickoff_returner_player_name,kickoff_returner_player_id,lateral_kickoff_returner_player_id,lateral_kickoff_returner_player_name,punter_player_id,punter_player_name,kicker_player_name,kicker_player_id,own_kickoff_recovery_player_id,own_kickoff_recovery_player_name,blocked_player_id,blocked_player_name,tackle_for_loss_1_player_id,tackle_for_loss_1_player_name,tackle_for_loss_2_player_id,tackle_for_loss_2_player_name,qb_hit_1_player_id,qb_hit_1_player_name,qb_hit_2_player_id,qb_hit_2_player_name,forced_fumble_player_1_team,forced_fumble_player_1_player_id,forced_fumble_player_1_player_name,forced_fumble_player_2_team,forced_fumble_player_2_player_id,forced_fumble_player_2_player_name,solo_tackle_1_team,solo_tackle_2_team,solo_tackle_1_player_id,solo_tackle_2_player_id,solo_tackle_1_player_name,solo_tackle_2_player_name,assist_tackle_1_player_id,assist_tackle_1_player_name,assist_tackle_1_team,assist_tackle_2_player_id,assist_tackle_2_player_name,assist_tackle_2_team,assist_tackle_3_player_id,assist_tackle_3_player_name,assist_tackle_3_team,assist_tackle_4_player_id,assist_tackle_4_player_name,assist_tackle_4_team,pass_defense_1_player_id,pass_defense_1_player_name,pass_defense_2_player_id,pass_defense_2_player_name,fumbled_1_team,fumbled_1_player_id,fumbled_1_player_name,fumbled_2_player_id,fumbled_2_player_name,fumbled_2_team,fumble_recovery_1_team,fumble_recovery_1_yards,fumble_recovery_1_player_id,fumble_recovery_1_player_name,fumble_recovery_2_team,fumble_recovery_2_yards,fumble_recovery_2_player_id,fumble_recovery_2_player_name,return_team,return_yards,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,900.0,1800.0,3600.0,Half1,0,1,0,1,NaN,0.0,15:00,TEN 30,0,0,R.Bironas kicks 67 yards from TEN 30 to PIT 3....,kickoff,0.0,0,0,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.0,NaN,NaN,3,3,0.0,NaN,NaN,3.0,3.0,0,0,NaN,NaN,NaN,0.0,0.0,0.0,0.001506,0.179749,0.006639,0.281138,0.213700,0.003592,0.313676,0.0,0.0,0.323526,2.014474,2.014474,-2.014474,0.00000,0.00000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S.Logan,00-0026491,NaN,NaN,NaN,NaN,R.Bironas,00-0020962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEN,NaN,00-0025406,NaN,M.Griffin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PIT,39.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10,893.0,1793.0,3593.0,Half1,0,1,0,1,1.0,0.0,14:53,PIT 42,10,5,(14:53) B.Roethlisberger pass short left to H....,pass,5.0,0,0,1.0,0,0,0,short,left,-3.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,3,3,0.0,NaN,NaN,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000969,0.108505,0.001061,0.169117,0.293700,0.003638,0.423011,0.0,0.0,2.338000,0.077907,2.092381,-2.092381,0.00000,0.00000,0.077907,-0.077907,-0.938735,1.016643,-0.938735,1.016643,-0.938735,0.938735,1.016643,-1.016643,-0.938735,0.938735,1.016643,-1.016643,0.546433,0.453567,0.546433,0.453567,0.004655,0.551088,0.448912,0.000000,0.000000,0.004655,-0.004655,-0.028383,0.033038,-0.028383,0.033038,-0.028383,0.028383,0.033038,-0.033038,-0.028383,0.028383,0.033038,-0.033038,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0022924,B.Roethlisberger,00-0017162,H.Ward,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEN,NaN,00-0021219,NaN,C.Hope,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10,856.0,1756.0,3556.0,Half1,0,1,0,1,2.0,0.0,14:16,PIT 47,5,2,(14:16) W.Parker right end to PIT 44 for -3 ya...,run,-3.0,0,0,0.0,0,0,0,NaN,NaN,NaN,NaN,right,end,NaN,NaN,NaN,NaN,3,3,0.0,NaN,NaN,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.001057,0.105106,0.000981,0.162747,0.304805,0.003826,0.421478,0.0,0.0,2.415907,-1.402760,0.689621,-0.689621,-1.40276,1.40276,0.077907,-0.077907,NaN,NaN,0.000000,0.000000,-0.938735,0.938735,1.016643,-1.016643,-0.938735,0.938735,1.016643,-1.016643,0.551088,0.448912,0.551088,0.448912,-0.040295,0.510793,0.489207,-0.040295,0.040295,0.004655,-0.004655,NaN,NaN,0.000000,0.000000,-0.028383,0.028383,0.033038,-0.033038,-0.028383,0.028383,0.033038,-0.033038,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,00-0022250,W.Parker,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00-0024331,S.Tulloch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TEN,NaN,00-0024331,NaN,S.Tulloch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,815.0,1715.0,3515.0,Half1,0,1,0,1,3.0,0.0,13:35,PIT 44,8,2,(13:35) (Shotgun) B.Roethlisberger pass incomp...,pass,0.0,1,0,1.0,0,0,0,deep,right,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,0.0,NaN,NaN,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.001434,0.149088,0.001944,0.234801,0.289336,0.004776,0.318621,0.0,0.0,1.013147,-1.712583,-1.022962,1.022962,-1.40276,1.40276,-1.634676,1.634676,3.412572,-5.125156,0.000000,0.000000,-0.938735,0.938735,1.016643,-1.016643,2.473837,-2.473837,-4.108513,4.108513,0.510793,0.489207,0.510793,0.489207,-0.049576,0.461217,0.538783,-0.040295,0.040295,-0.044921,0.044921,0.109925,-0.159501,0.000000,0.000000,-0.028383,0.028383,0.033038,-0.033038,0.081542,-0.081542,-0.126463,0.126463,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,00-0022924,B.Roethlisberger,00-0026901,M.Wallace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,807.0,1707.0,3507.0,Half1,0,1,0,1,4.0,0.0,13:27,PIT 44,8,2,(13:27) (Punt formation) D.Sepulveda punts 54 ...,punt,0.0,0,0,0.0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.0,NaN,NaN,3,3,0.0,NaN,NaN,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.001861,0.213480,0.003279,0.322262,0.244603,0.006404,0.208111,0.0,0.0,-0.699436,2.097796,1.074834,-1.074834,-1.40276,1.40276,-1.634676,1.634676,NaN,NaN,0.000000,0.000000,-0.938735,0.938735,1.016643,-1.016643,2.473837,-2.473837,-4.108513,4.108513,0.461217,0.538783,0.461217,0.538783,0.097712,0.558929,0.441071,-0.040295,0.040295,-0.044921,0.044921,NaN,NaN,0.000000,0.000000,-0.028383,0.028383,0.033038,-0.033038,0.081542,-0.081542,-0.126463,0.126463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00-0025499,D.Sepulveda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0

In [84]:
passes = nfl[['game_id', 'play_type', 'yards_gained', 
           'shotgun', 'qb_dropback', 
           'qb_scramble', 'pass_length',
           'air_yards', 'pass_location',
          'yards_after_catch','first_down_pass','incomplete_pass',
          'interception','safety','tackled_for_loss','qb_hit', 'pass_attempt',
          'sack','touchdown','pass_touchdown','fumble', 'complete_pass','lateral_reception',
          'passer_player_id','passer_player_name','receiver_player_id','receiver_player_name']]

passes2 = nfl[['game_id', 'play_type', 'yards_gained', 
           'shotgun', 'qb_dropback', 
           'qb_scramble', 'pass_length',
           'air_yards', 'pass_location',
          'yards_after_catch','td_team',
          'total_home_pass_epa','total_away_pass_epa',
          'air_epa', 'yac_epa', 'comp_air_epa',
          'comp_yac_epa', 'total_home_comp_air_epa',
          'total_away_comp_air_epa','total_home_comp_yac_epa',
          'total_away_comp_yac_epa', 'total_home_raw_air_epa',
          'total_away_raw_air_epa', 'total_home_raw_yac_epa',
          'total_away_raw_yac_epa','first_down_pass','incomplete_pass',
          'interception','fumble_forced','fumble_not_forced','fumble_out_of_bounds',
          'solo_tackle','safety','tackled_for_loss','fumble_lost','qb_hit', 'pass_attempt',
          'sack','touchdown','pass_touchdown','fumble', 'complete_pass','lateral_reception',
          'passer_player_id','passer_player_name','receiver_player_id','receiver_player_name',
          'lateral_receiver_player_id','lateral_receiver_player_name','lateral_sack_player_id',
          'lateral_sack_player_name','interception_player_id','interception_player_name',
          'lateral_interception_player_id','lateral_interception_player_name','qb_hit_1_player_id',
          'qb_hit_1_player_name','qb_hit_2_player_id','qb_hit_2_player_name','pass_defense_1_player_id',
          'pass_defense_1_player_name','pass_defense_2_player_id','pass_defense_2_player_name']]

runners = nfl[['run_location','run_gap','td_team','total_home_rush_epa',
           'total_away_rush_epa','first_down_rush','fumble_forced','fumble_not_forced',
           'fumble_out_of_bounds','solo_tackle','safety','tackled_for_loss','fumble_lost',
           'rush_attempt','rush_touchdown','fumble','lateral_rush','rusher_player_id','rusher_player_name']]

runners2 = nfl[['run_location','run_gap','td_team','total_home_rush_epa',
           'total_away_rush_epa','first_down_rush','fumble_forced','fumble_not_forced',
           'fumble_out_of_bounds','solo_tackle','safety','tackled_for_loss','fumble_lost',
           'rush_attempt','rush_touchdown','fumble','lateral_rush','rusher_player_id','rusher_player_name',
           'lateral_rusher_player_id','lateral_rusher_player_name','tackle_for_loss_1_player_id','tackle_for_loss_1_player_name',
           'tackle_for_loss_2_player_id','tackle_for_loss_2_player_name','forced_fumble_player_1_team',
           'forced_fumble_player_1_player_id','forced_fumble_player_1_player_name','forced_fumble_player_2_team',
           'forced_fumble_player_2_player_id','forced_fumble_player_2_player_name','solo_tackle_1_team','solo_tackle_2_team',
           'solo_tackle_1_player_id','solo_tackle_2_player_id','solo_tackle_1_player_name','solo_tackle_2_player_name',
           'assist_tackle_1_player_id','assist_tackle_1_player_name','assist_tackle_1_team','assist_tackle_2_player_id',
           'assist_tackle_2_player_name','assist_tackle_2_team','assist_tackle_3_player_id','assist_tackle_3_player_name',
           'assist_tackle_3_team','assist_tackle_4_player_id','assist_tackle_4_player_name','assist_tackle_4_team']]

In [85]:
p1 = passes[passes['play_type'] == 'pass']

p2 = p1[p1['game_id'] == 2009091000]
p2

,game_id,play_type,yards_gained,shotgun,qb_dropback,qb_scramble,pass_length,air_yards,pass_location,yards_after_catch,first_down_pass,incomplete_pass,interception,safety,tackled_for_loss,qb_hit,pass_attempt,sack,touchdown,pass_touchdown,fumble,complete_pass,lateral_reception,passer_player_id,passer_player_name,receiver_player_id,receiver_player_name
1,2009091000,pass,5.0,0,1.0,0,short,-3.0,left,8.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,00-0022924,B.Roethlisberger,00-0017162,H.Ward
3,2009091000,pass,0.0,1,1.0,0,deep,34.0,right,NaN,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,00-0022924,B.Roethlisberger,00-0026901,M.Wallace
6,2009091000,pass,4.0,0,1.0,0,short,3.0,left,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,00-0003292,K.Collins,00-0024489,A.Hall
9,2009091000,pass,3.0,0,1.0,0,short,-2.0,right,5.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,00-0022924,B.Roethlisberger,00-0026901,M.Wallace
10,2009091000,pass,10.0,0,1.0,0,short,-1.0,left,11.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,00-0022924,B.Roethlisberger,00-0024240,S.Holmes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,2009091000,pass,8.0,1,1.0,0,short,7.0,left,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,00-0022924,B.Roethlisberger,00-0023465,H.Miller
172,2009091000,pass,8.0,1,1.0,0,short,4.0,right,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,00-0022924,B.Roethlisberger,00-0017162,H.Ward
173,2009091000,pass,11.0,1,1.0,0,short,7.0,middle,4.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,00-0022924,B.Roethlisberger,00-0024240,S.Holmes
174,2009091000,pass,0.0,1,1.0,0,short,12.0,middle,NaN,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,00-0022924,B.Roethlisberger,00-0017162,H.Ward
175,2009091000,pass,22.0,1,1.0,0,deep,22.0,middle,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,00-0022924,B.Roethlisberger,00-0026901,M.Wallace

In [86]:
p2.corr()

,game_id,yards_gained,shotgun,qb_dropback,qb_scramble,air_yards,yards_after_catch,first_down_pass,incomplete_pass,interception,safety,tackled_for_loss,qb_hit,pass_attempt,sack,touchdown,pass_touchdown,fumble,complete_pass,lateral_reception
game_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
yards_gained,NaN,1.000000,0.099638,NaN,NaN,0.351571,0.386563,0.603700,-0.375001,-0.128885,NaN,NaN,-0.290542,NaN,-0.430596,0.270784,0.270784,0.137842,0.606773,NaN
shotgun,NaN,0.099638,1.000000,NaN,NaN,0.354859,-0.082437,0.036564,0.112354,0.025426,NaN,NaN,0.225058,NaN,0.102221,0.127657,0.127657,-0.032881,-0.163106,NaN
qb_dropback,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
qb_scramble,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
air_yards,NaN,0.351571,0.354859,NaN,NaN,1.000000,-0.134140,0.139578,0.010660,0.526437,NaN,NaN,0.038007,NaN,NaN,0.220860,0.220860,-0.007362,-0.232228,NaN
yards_after_catch,NaN,0.386563,-0.082437,NaN,NaN,-0.134140,1.000000,-0.047392,NaN,NaN,NaN,NaN,-0.119176,NaN,NaN,-0.150895,-0.150895,0.135285,NaN,NaN
first_down_pass,NaN,0.603700,0.036564,NaN,NaN,0.139578,-0.047392,1.000000,-0.446308,-0.153393,NaN,NaN,-0.065048,NaN,-0.200552,0.198373,0.198373,-0.124469,0.565181,NaN
incomplete_pass,NaN,-0.375001,0.112354,NaN,NaN,0.010660,NaN,-0.446308,1.000000,-0.109109,NaN,NaN,-0.035451,NaN,-0.142653,-0.088535,-0.088535,-0.088535,-0.789673,NaN
interception,NaN,-0.128885,0.025426,NaN,NaN,0.526437,NaN,-0.153393,-0.109109,1.000000,NaN,NaN,-0.071673,NaN,-0.049029,-0.030429,-0.030429,-0.030429,-0.271405,NaN
safety,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tackled_for_loss,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
qb_hit,NaN,-0.290542,0.225058,NaN,NaN,0.038007,-0.119176,-0.065048,-0.035451,-0.071673,NaN,NaN,1.000000,NaN,0.684068,0.183198,0.183198,-0.058158,-0.283886,NaN
pass_attempt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sack,NaN,-0.430596,0.102221,NaN,NaN,NaN,NaN,-0.200552,-0.142653,-0.049029,NaN,NaN,0.684068,NaN,1.000000,-0.039784,-0.039784,-0.039784,-0.354846,NaN
touchdown,NaN,0.270784,0.127657,NaN,NaN,0.220860,-0.150895,0.198373,-0.088535,-0.030429,NaN,NaN,0.183198,NaN,-0.039784,1.000000,1.000000,-0.024691,0.112117,NaN
pass_touchdown,NaN,0.270784,0.127657,NaN,NaN,0.220860,-0.150895,0.198373,-0.088535,-0.030429,NaN,NaN,0.183198,NaN,-0.039784,1.000000,1.000000,-0.024691,0.112117,NaN
fumble,NaN,0.137842,-0.032881,NaN,NaN,-0.007362,0.135285,-0.124469,-0.088535,-0.030429,NaN,NaN,-0.058158,NaN,-0.039784,-0.024691,-0.024691,1.000000,0.112117,NaN
complete_pass,NaN,0.606773,-0.163106,NaN,NaN,-0.232228,NaN,0.565181,-0.789673,-0.271405,NaN,NaN,-0.283886,NaN,-0.354846,0.112117,0.112117,0.112117,1.000000,NaN
lateral_reception,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
p2.describe()

,game_id,yards_gained,shotgun,qb_dropback,qb_scramble,air_yards,yards_after_catch,first_down_pass,incomplete_pass,interception,safety,tackled_for_loss,qb_hit,pass_attempt,sack,touchdown,pass_touchdown,fumble,complete_pass,lateral_reception
count,8.300000e+01,83.000000,83.000000,83.0,83.0,78.00000,55.000000,83.000000,83.000000,83.000000,83.0,83.0,83.000000,83.0,83.000000,83.000000,83.000000,83.000000,83.000000,83.0
mean,2.009091e+09,6.686747,0.602410,1.0,0.0,9.00000,3.690909,0.385542,0.240964,0.036145,0.0,0.0,0.120482,1.0,0.060241,0.024096,0.024096,0.024096,0.662651,0.0
std,0.000000e+00,10.107867,0.492375,0.0,0.0,11.08878,4.795340,0.489682,0.430268,0.187784,0.0,0.0,0.327503,0.0,0.239379,0.154281,0.154281,0.154281,0.475679,0.0
min,2.009091e+09,-19.000000,0.000000,1.0,0.0,-7.00000,-11.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,2.009091e+09,0.000000,0.000000,1.0,0.0,2.00000,1.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
50%,2.009091e+09,5.000000,1.000000,1.0,0.0,6.50000,3.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.0
75%,2.009091e+09,10.500000,1.000000,1.0,0.0,13.75000,5.500000,1.000000,0.000000,0.000000,0.0,0.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.0
max,2.009091e+09,57.000000,1.000000,1.0,0.0,55.00000,21.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.0

In [88]:
list(nfl.columns)

['play_id',
 'game_id',
 'home_team',
 'away_team',
 'posteam',
 'posteam_type',
 'defteam',
 'side_of_field',
 'yardline_100',
 'game_date',
 'quarter_seconds_remaining',
 'half_seconds_remaining',
 'game_seconds_remaining',
 'game_half',
 'quarter_end',
 'drive',
 'sp',
 'qtr',
 'down',
 'goal_to_go',
 'time',
 'yrdln',
 'ydstogo',
 'ydsnet',
 'desc',
 'play_type',
 'yards_gained',
 'shotgun',
 'no_huddle',
 'qb_dropback',
 'qb_kneel',
 'qb_spike',
 'qb_scramble',
 'pass_length',
 'pass_location',
 'air_yards',
 'yards_after_catch',
 'run_location',
 'run_gap',
 'field_goal_result',
 'kick_distance',
 'extra_point_result',
 'two_point_conv_result',
 'home_timeouts_remaining',
 'away_timeouts_remaining',
 'timeout',
 'timeout_team',
 'td_team',
 'posteam_timeouts_remaining',
 'defteam_timeouts_remaining',
 'total_home_score',
 'total_away_score',
 'posteam_score',
 'defteam_score',
 'score_differential',
 'posteam_score_post',
 'defteam_score_post',
 'score_differential_post',
 'no_score_prob',
 'opp_fg_prob',
 'opp_safety_prob',
 'opp_td_prob',
 'fg_prob',
 'safety_prob',
 'td_prob',
 'extra_point_prob',
 'two_point_conversion_prob',
 'ep',
 'epa',
 'total_home_epa',
 'total_away_epa',
 'total_home_rush_epa',
 'total_away_rush_epa',
 'total_home_pass_epa',
 'total_away_pass_epa',
 'air_epa',
 'yac_epa',
 'comp_air_epa',
 'comp_yac_epa',
 'total_home_comp_air_epa',
 'total_away_comp_air_epa',
 'total_home_comp_yac_epa',
 'total_away_comp_yac_epa',
 'total_home_raw_air_epa',
 'total_away_raw_air_epa',
 'total_home_raw_yac_epa',
 'total_away_raw_yac_epa',
 'wp',
 'def_wp',
 'home_wp',
 'away_wp',
 'wpa',
 'home_wp_post',
 'away_wp_post',
 'total_home_rush_wpa',
 'total_away_rush_wpa',
 'total_home_pass_wpa',
 'total_away_pass_wpa',
 'air_wpa',
 'yac_wpa',
 'comp_air_wpa',
 'comp_yac_wpa',
 'total_home_comp_air_wpa',
 'total_away_comp_air_wpa',
 'total_home_comp_yac_wpa',
 'total_away_comp_yac_wpa',
 'total_home_raw_air_wpa',
 'total_away_raw_air_wpa',
 'total_home_raw_yac_wpa',
 'total_away_raw_yac_wpa',
 'punt_blocked',
 'first_down_rush',
 'first_down_pass',
 'first_down_penalty',
 'third_down_converted',
 'third_down_failed',
 'fourth_down_converted',
 'fourth_down_failed',
 'incomplete_pass',
 'interception',
 'punt_inside_twenty',
 'punt_in_endzone',
 'punt_out_of_bounds',
 'punt_downed',
 'punt_fair_catch',
 'kickoff_inside_twenty',
 'kickoff_in_endzone',
 'kickoff_out_of_bounds',
 'kickoff_downed',
 'kickoff_fair_catch',
 'fumble_forced',
 'fumble_not_forced',
 'fumble_out_of_bounds',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'fumble_lost',
 'own_kickoff_recovery',
 'own_kickoff_recovery_td',
 'qb_hit',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'extra_point_attempt',
 'two_point_attempt',
 'field_goal_attempt',
 'kickoff_attempt',
 'punt_attempt',
 'fumble',
 'complete_pass',
 'assist_tackle',
 'lateral_reception',
 'lateral_rush',
 'lateral_return',
 'lateral_recovery',
 'passer_player_id',
 'passer_player_name',
 'receiver_player_id',
 'receiver_player_name',
 'rusher_player_id',
 'rusher_player_name',
 'lateral_receiver_player_id',
 'lateral_receiver_player_name',
 'lateral_rusher_player_id',
 'lateral_rusher_player_name',
 'lateral_sack_player_id',
 'lateral_sack_player_name',
 'interception_player_id',
 'interception_player_name',
 'lateral_interception_player_id',
 'lateral_interception_player_name',
 'punt_returner_player_id',
 'punt_returner_player_name',
 'lateral_punt_returner_player_id',
 'lateral_punt_returner_player_name',
 'kickoff_returner_player_name',
 'kickoff_returner_player_id',
 'lateral_kickoff_returner_player_id',
 'lateral_kickoff_returner_player_name',
 'punter_player_id',
 'punter_player_name',
 'kicker_player_name',
 'kicker_player_id',
 'own_kickoff_recovery_player_id',
 'own_kickoff_recovery_player_name',
 'blocked_player_id',
 'blocked_player_name',
 'tackle_for_loss_1_player_id',
 'tackle_for_loss_1_player_name',
 'tackle_for_loss_2_player_id',
 'tackle_for_loss_2_player_name',
 'qb_hit_1_player_id',
 'qb_hit_1_player_name',
 'qb_hit_2_player_id',
 'qb_hit_2_player_name',
 'forced_fumble_player_1_team',
 'forced_fumble_player_1_player_id',
 'forced_fumble_player_1_player_name',
 'forced_fumble_player_2_team',
 'forced_fumble_player_2_player_id',
 'forced_fumble_player_2_player_name',
 'solo_tackle_1_team',
 'solo_tackle_2_team',
 'solo_tackle_1_player_id',
 'solo_tackle_2_player_id',
 'solo_tackle_1_player_name',
 'solo_tackle_2_player_name',
 'assist_tackle_1_player_id',
 'assist_tackle_1_player_name',
 'assist_tackle_1_team',
 'assist_tackle_2_player_id',
 'assist_tackle_2_player_name',
 'assist_tackle_2_team',
 'assist_tackle_3_player_id',
 'assist_tackle_3_player_name',
 'assist_tackle_3_team',
 'assist_tackle_4_player_id',
 'assist_tackle_4_player_name',
 'assist_tackle_4_team',
 'pass_defense_1_player_id',
 'pass_defense_1_player_name',
 'pass_defense_2_player_id',
 'pass_defense_2_player_name',
 'fumbled_1_team',
 'fumbled_1_player_id',
 'fumbled_1_player_name',
 'fumbled_2_player_id',
 'fumbled_2_player_name',
 'fumbled_2_team',
 'fumble_recovery_1_team',
 'fumble_recovery_1_yards',
 'fumble_recovery_1_player_id',
 'fumble_recovery_1_player_name',
 'fumble_recovery_2_team',
 'fumble_recovery_2_yards',
 'fumble_recovery_2_player_id',
 'fumble_recovery_2_player_name',
 'return_team',
 'return_yards',
 'penalty_team',
 'penalty_player_id',
 'penalty_player_name',
 'penalty_yards',
 'replay_or_challenge',
 'replay_or_challenge_result',
 'penalty_type',
 'defensive_two_point_attempt',
 'defensive_two_point_conv',
 'defensive_extra_point_attempt',
 'defensive_extra_point_conv']

In [89]:
df1 = nfl[[ 'play_id',
            'game_id',
            'home_team',
            'away_team',
            'posteam',
            'posteam_type',
            'defteam',
            'side_of_field',
            'yardline_100',
            'game_date' ]]

df2 = nfl[[ 'quarter_seconds_remaining',
            'half_seconds_remaining',
            'game_seconds_remaining',
            'game_half',
            'quarter_end',
            'drive',
            'sp',
            'qtr',
            'down',
            'goal_to_go',
            'time',
            'yrdln',
            'ydstogo' ]]

df3 = nfl[[ 'ydsnet',
            'desc',
            'play_type',
            'yards_gained',
            'shotgun',
            'no_huddle',
            'qb_dropback',
            'qb_kneel',
            'qb_spike',
            'qb_scramble',
            'pass_length',
            'pass_location' ]]

df4 = nfl[[ 'air_yards',
            'yards_after_catch',
            'run_location',
            'run_gap',
            'field_goal_result',
            'kick_distance',
            'extra_point_result',
            'two_point_conv_result',
            'home_timeouts_remaining',
            'away_timeouts_remaining',
            'timeout',
            'timeout_team',
            'td_team' ]]

df5 = nfl[[ 'posteam_timeouts_remaining',
            'defteam_timeouts_remaining',
            'total_home_score',
            'total_away_score',
            'posteam_score',
            'defteam_score',
            'score_differential',
            'posteam_score_post',
            'defteam_score_post',
            'score_differential_post' ]]

df6 = nfl[[ 'no_score_prob',
            'opp_fg_prob',
            'opp_safety_prob',
            'opp_td_prob',
            'fg_prob',
            'safety_prob',
            'td_prob',
            'extra_point_prob',
            'two_point_conversion_prob' ]]


df7 = nfl[[ 'ep',
            'epa',
            'total_home_epa',
            'total_away_epa',
            'total_home_rush_epa',
            'total_away_rush_epa',
            'total_home_pass_epa',
            'total_away_pass_epa',
            'air_epa',
            'yac_epa',
            'comp_air_epa',
            'comp_yac_epa' ]]

df8 = nfl[[ 'total_home_comp_air_epa',
            'total_away_comp_air_epa',
            'total_home_comp_yac_epa',
            'total_away_comp_yac_epa',
            'total_home_raw_air_epa',
            'total_away_raw_air_epa',
            'total_home_raw_yac_epa',
            'total_away_raw_yac_epa' ]]


df9 = nfl[[  'punt_blocked',
            'first_down_rush',
            'first_down_pass',
            'first_down_penalty',
            'third_down_converted',
            'third_down_failed',
            'fourth_down_converted',
            'fourth_down_failed',
            'incomplete_pass',
            'interception',
            'punt_inside_twenty',
            'punt_in_endzone',
            'punt_out_of_bounds',
            'punt_downed',
            'punt_fair_catch' ]]


df10 = nfl[[ 'kickoff_inside_twenty',
            'kickoff_in_endzone',
            'kickoff_out_of_bounds',
            'kickoff_downed',
            'kickoff_fair_catch',
            'fumble_forced',
            'fumble_not_forced',
            'fumble_out_of_bounds',
            'solo_tackle',
            'safety',
            'penalty',
            'tackled_for_loss',
            'fumble_lost',
            'own_kickoff_recovery',
            'own_kickoff_recovery_td',
            'qb_hit',
            'rush_attempt',
            'pass_attempt',
            'sack',
            'touchdown',
            'pass_touchdown',
            'rush_touchdown',
            'return_touchdown' ]]


df11 = nfl[['extra_point_attempt',
            'two_point_attempt',
            'field_goal_attempt',
            'kickoff_attempt',
            'punt_attempt',
            'fumble',
            'complete_pass',
            'assist_tackle',
            'lateral_reception',
            'lateral_rush',
            'lateral_return',
            'lateral_recovery',
            'passer_player_id',
            'passer_player_name',
            'receiver_player_id',
            'receiver_player_name',
            'rusher_player_id',
            'rusher_player_name']]

df12 = nfl[[ 'lateral_receiver_player_id',
            'lateral_receiver_player_name',
            'lateral_rusher_player_id',
            'lateral_rusher_player_name',
            'lateral_sack_player_id',
            'lateral_sack_player_name',
            'interception_player_id',
            'interception_player_name',
            'lateral_interception_player_id',
            'lateral_interception_player_name',
            'punt_returner_player_id',
            'punt_returner_player_name',
            'lateral_punt_returner_player_id',
            'lateral_punt_returner_player_name',
            'kickoff_returner_player_name',
            'kickoff_returner_player_id',
            'lateral_kickoff_returner_player_id',
            'lateral_kickoff_returner_player_name' ]]

df13 = nfl[[ 'punter_player_id',
            'punter_player_name',
            'kicker_player_name',
            'kicker_player_id',
            'own_kickoff_recovery_player_id',
            'own_kickoff_recovery_player_name',
            'blocked_player_id',
            'blocked_player_name',
            'tackle_for_loss_1_player_id',
            'tackle_for_loss_1_player_name',
            'tackle_for_loss_2_player_id',
            'tackle_for_loss_2_player_name',
            'qb_hit_1_player_id',
            'qb_hit_1_player_name',
            'qb_hit_2_player_id',
            'qb_hit_2_player_name' ]]

df14 = nfl[[ 'forced_fumble_player_1_team',
            'forced_fumble_player_1_player_id',
            'forced_fumble_player_1_player_name',
            'forced_fumble_player_2_team',
            'forced_fumble_player_2_player_id',
            'forced_fumble_player_2_player_name',
            'solo_tackle_1_team',
            'solo_tackle_2_team',
            'solo_tackle_1_player_id',
            'solo_tackle_2_player_id',
            'solo_tackle_1_player_name',
            'solo_tackle_2_player_name',
            'assist_tackle_1_player_id',
            'assist_tackle_1_player_name',
            'assist_tackle_1_team',
            'assist_tackle_2_player_id',
            'assist_tackle_2_player_name',
            'assist_tackle_2_team',
            'assist_tackle_3_player_id',
            'assist_tackle_3_player_name',
            'assist_tackle_3_team',
            'assist_tackle_4_player_id',
            'assist_tackle_4_player_name',
            'assist_tackle_4_team',
            'pass_defense_1_player_id',
            'pass_defense_1_player_name',
            'pass_defense_2_player_id',
            'pass_defense_2_player_name' ]]

df15 = nfl[[ 'fumbled_1_team',
            'fumbled_1_player_id',
            'fumbled_1_player_name',
            'fumbled_2_player_id',
            'fumbled_2_player_name',
            'fumbled_2_team',
            'fumble_recovery_1_team',
            'fumble_recovery_1_yards',
            'fumble_recovery_1_player_id',
            'fumble_recovery_1_player_name',
            'fumble_recovery_2_team',
            'fumble_recovery_2_yards',
            'fumble_recovery_2_player_id',
            'fumble_recovery_2_player_name',
            'return_team',
            'return_yards',
            'penalty_team',
            'penalty_player_id',
            'penalty_player_name',
            'penalty_yards',
            'replay_or_challenge',
            'replay_or_challenge_result',
            'penalty_type',
            'defensive_two_point_attempt',
            'defensive_two_point_conv',
            'defensive_extra_point_attempt',
            'defensive_extra_point_conv' ]]

In [90]:
df1.head()

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10

In [91]:
df2.head()

,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo
0,900.0,1800.0,3600.0,Half1,0,1,0,1,NaN,0.0,15:00,TEN 30,0
1,893.0,1793.0,3593.0,Half1,0,1,0,1,1.0,0.0,14:53,PIT 42,10
2,856.0,1756.0,3556.0,Half1,0,1,0,1,2.0,0.0,14:16,PIT 47,5
3,815.0,1715.0,3515.0,Half1,0,1,0,1,3.0,0.0,13:35,PIT 44,8
4,807.0,1707.0,3507.0,Half1,0,1,0,1,4.0,0.0,13:27,PIT 44,8

In [92]:
df3.head()

,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location
0,0,R.Bironas kicks 67 yards from TEN 30 to PIT 3....,kickoff,0.0,0,0,0.0,0,0,0,NaN,NaN
1,5,(14:53) B.Roethlisberger pass short left to H....,pass,5.0,0,0,1.0,0,0,0,short,left
2,2,(14:16) W.Parker right end to PIT 44 for -3 ya...,run,-3.0,0,0,0.0,0,0,0,NaN,NaN
3,2,(13:35) (Shotgun) B.Roethlisberger pass incomp...,pass,0.0,1,0,1.0,0,0,0,deep,right
4,2,(13:27) (Punt formation) D.Sepulveda punts 54 ...,punt,0.0,0,0,0.0,0,0,0,NaN,NaN

In [93]:
df4.head()

,air_yards,yards_after_catch,run_location,run_gap,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,home_timeouts_remaining,away_timeouts_remaining,timeout,timeout_team,td_team
0,NaN,NaN,NaN,NaN,NaN,67.0,NaN,NaN,3,3,0.0,NaN,NaN
1,-3.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,3,3,0.0,NaN,NaN
2,NaN,NaN,right,end,NaN,NaN,NaN,NaN,3,3,0.0,NaN,NaN
3,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,0.0,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,54.0,NaN,NaN,3,3,0.0,NaN,NaN

In [94]:
df5.head()

,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post
0,3.0,3.0,0,0,NaN,NaN,NaN,0.0,0.0,0.0
1,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,3.0,3.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [95]:
df6.head()

,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob
0,0.001506,0.179749,0.006639,0.281138,0.213700,0.003592,0.313676,0.0,0.0
1,0.000969,0.108505,0.001061,0.169117,0.293700,0.003638,0.423011,0.0,0.0
2,0.001057,0.105106,0.000981,0.162747,0.304805,0.003826,0.421478,0.0,0.0
3,0.001434,0.149088,0.001944,0.234801,0.289336,0.004776,0.318621,0.0,0.0
4,0.001861,0.213480,0.003279,0.322262,0.244603,0.006404,0.208111,0.0,0.0

In [96]:
df7.head()

,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa
0,0.323526,2.014474,2.014474,-2.014474,0.00000,0.00000,0.000000,0.000000,NaN,NaN,0.000000,0.000000
1,2.338000,0.077907,2.092381,-2.092381,0.00000,0.00000,0.077907,-0.077907,-0.938735,1.016643,-0.938735,1.016643
2,2.415907,-1.402760,0.689621,-0.689621,-1.40276,1.40276,0.077907,-0.077907,NaN,NaN,0.000000,0.000000
3,1.013147,-1.712583,-1.022962,1.022962,-1.40276,1.40276,-1.634676,1.634676,3.412572,-5.125156,0.000000,0.000000
4,-0.699436,2.097796,1.074834,-1.074834,-1.40276,1.40276,-1.634676,1.634676,NaN,NaN,0.000000,0.000000

In [97]:
df8.head()

,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,-0.938735,0.938735,1.016643,-1.016643,-0.938735,0.938735,1.016643,-1.016643
2,-0.938735,0.938735,1.016643,-1.016643,-0.938735,0.938735,1.016643,-1.016643
3,-0.938735,0.938735,1.016643,-1.016643,2.473837,-2.473837,-4.108513,4.108513
4,-0.938735,0.938735,1.016643,-1.016643,2.473837,-2.473837,-4.108513,4.108513

In [98]:
df9.head()

,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [99]:
df10.head()

,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [100]:
df11.head()

,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passer_player_id,passer_player_name,receiver_player_id,receiver_player_name,rusher_player_id,rusher_player_name
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0022924,B.Roethlisberger,00-0017162,H.Ward,NaN,NaN
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,00-0022250,W.Parker
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,00-0022924,B.Roethlisberger,00-0026901,M.Wallace,NaN,NaN
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
df12.head()

,lateral_receiver_player_id,lateral_receiver_player_name,lateral_rusher_player_id,lateral_rusher_player_name,lateral_sack_player_id,lateral_sack_player_name,interception_player_id,interception_player_name,lateral_interception_player_id,lateral_interception_player_name,punt_returner_player_id,punt_returner_player_name,lateral_punt_returner_player_id,lateral_punt_returner_player_name,kickoff_returner_player_name,kickoff_returner_player_id,lateral_kickoff_returner_player_id,lateral_kickoff_returner_player_name
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S.Logan,00-0026491,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
df13.head()

,punter_player_id,punter_player_name,kicker_player_name,kicker_player_id,own_kickoff_recovery_player_id,own_kickoff_recovery_player_name,blocked_player_id,blocked_player_name,tackle_for_loss_1_player_id,tackle_for_loss_1_player_name,tackle_for_loss_2_player_id,tackle_for_loss_2_player_name,qb_hit_1_player_id,qb_hit_1_player_name,qb_hit_2_player_id,qb_hit_2_player_name
0,NaN,NaN,R.Bironas,00-0020962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00-0024331,S.Tulloch,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00-0025499,D.Sepulveda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
df14.head()

,forced_fumble_player_1_team,forced_fumble_player_1_player_id,forced_fumble_player_1_player_name,forced_fumble_player_2_team,forced_fumble_player_2_player_id,forced_fumble_player_2_player_name,solo_tackle_1_team,solo_tackle_2_team,solo_tackle_1_player_id,solo_tackle_2_player_id,solo_tackle_1_player_name,solo_tackle_2_player_name,assist_tackle_1_player_id,assist_tackle_1_player_name,assist_tackle_1_team,assist_tackle_2_player_id,assist_tackle_2_player_name,assist_tackle_2_team,assist_tackle_3_player_id,assist_tackle_3_player_name,assist_tackle_3_team,assist_tackle_4_player_id,assist_tackle_4_player_name,assist_tackle_4_team,pass_defense_1_player_id,pass_defense_1_player_name,pass_defense_2_player_id,pass_defense_2_player_name
0,NaN,NaN,NaN,NaN,NaN,NaN,TEN,NaN,00-0025406,NaN,M.Griffin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,TEN,NaN,00-0021219,NaN,C.Hope,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,TEN,NaN,00-0024331,NaN,S.Tulloch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
df15.head()

,fumbled_1_team,fumbled_1_player_id,fumbled_1_player_name,fumbled_2_player_id,fumbled_2_player_name,fumbled_2_team,fumble_recovery_1_team,fumble_recovery_1_yards,fumble_recovery_1_player_id,fumble_recovery_1_player_name,fumble_recovery_2_team,fumble_recovery_2_yards,fumble_recovery_2_player_id,fumble_recovery_2_player_name,return_team,return_yards,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PIT,39.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0